### products index
GET http://localhost:3000/products.json
Authorization: Bearer 

### products show
GET http://localhost:3000/products/10.json
Content-Type: application/json

{
  "email": "jake@email.com",
  "password": "password"
}

### products create
POST http://localhost:3000/products.json
# Authorization: Bearer 
Content-type: application/json

{
  "name": "hat",
  "price": 15,
  "description": "a fun hat you wear on your head",
  "inventory": 5,
  "supplier_id": 4
}

### products update
PATCH http://localhost:3000/products/11.json
Content-type: application/json

{
  "name": "Book",
  "price": 17,
  "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrBstXAmkzVK-Ze6Lg_gZMVl57-7Oyvpw6QA&usqp=CAU",
  "description": "a book you can read",
  "inventory": 5,
  "supplier_id": 3
}

### products delete
DELETE http://localhost:3000/products/8.json

### CREATE USER
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Liz",
  "email": "liz@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### SESSIONS CREATE (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "maria@email.com",
  "password": "password"
}

### ORDERS CREATE
POST http://localhost:3000/orders.json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjcxNjQ3NDc1fQ.hcGhhAySGOpXraMJOgfyFMdxF7cYrhdxZCQrkTpT2eQ
Content-Type: application/json


### SHOW ORDER
GET http://localhost:3000/orders/12.json 
Authorization: Bearer 

### SHOW ORDERS
GET http://localhost:3000/orders.json 
Authorization: Bearer 

### create cart
POST http://localhost:3000/carted_products.json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjcxNjQzNjYyfQ.fnbWPdPBBaE3zuLuFNxnzrwY-krjqPj9KVSqdNbYOTU
Content-Type: application/json

{
  "product_id": 7,
  "quantity": 1
}

### carted products index
GET http://localhost:3000/carted_products.json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjcxNjQ0MjM4fQ.YEwOBjGEoroeCXWUuwf2AmhkriSBsedM4TAkaoXBTeE

### delete from cart
DELETE http://localhost:3000/carted_products/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjcxNjQ0MjM4fQ.YEwOBjGEoroeCXWUuwf2AmhkriSBsedM4TAkaoXBTeE
